Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np

a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [10]:
import numpy as np

a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [18]:
import numpy as np

a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[10  8  5  7  6]
 [ 2  2  3  4  2]
 [ 8  2  9  1  7]
 [ 1  6  5  8 10]
 [ 9  3  4  9  3]]
