1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np

a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [10]:
import numpy as np

a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [18]:
import numpy as np

a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[10  8  5  7  6]
 [ 2  2  3  4  2]
 [ 8  2  9  1  7]
 [ 1  6  5  8 10]
 [ 9  3  4  9  3]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.



In [18]:
import numpy as np

a = np.random.rand(4, 4)
print(a)

[[0.49043457 0.91415758 0.43671804 0.51764046]
 [0.09334513 0.01288577 0.12002006 0.72113882]
 [0.43707903 0.96296334 0.96184881 0.63998854]
 [0.193748   0.16142958 0.0488041  0.21080994]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [21]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)

print(a)
print(b)

print(a + b)
print(a - b)
print(a * b)

[ 8 10  3  3  2]
[6 4 7 9 7]
[14 14 10 12  9]
[ 2  6 -4 -6 -5]
[48 40 21 27 14]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

32


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [30]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
c = np.dot(a, b)

print(a)
print(b)
print(c)

[[9 5]
 [4 1]]
[[10  6  8]
 [ 1  7  4]]
[[95 89 92]
 [41 31 36]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.



In [35]:
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)

print(a)
print(a_inv)


[[5 2 9]
 [6 3 5]
 [9 6 8]]
[[-0.13333333  0.84444444 -0.37777778]
 [-0.06666667 -0.91111111  0.64444444]
 [ 0.2        -0.26666667  0.06666667]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.



In [36]:
a = np.random.rand(4, 4)

print(a)
b = a.T
print(b)

[[0.15363106 0.3539717  0.73037474 0.40765648]
 [0.07900831 0.06575923 0.93460031 0.98446639]
 [0.86103765 0.80993723 0.26151722 0.68214766]
 [0.86419933 0.05765161 0.44638747 0.84034107]]
[[0.15363106 0.07900831 0.86103765 0.86419933]
 [0.3539717  0.06575923 0.80993723 0.05765161]
 [0.73037474 0.93460031 0.26151722 0.44638747]
 [0.40765648 0.98446639 0.68214766 0.84034107]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [37]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
c = np.dot(a, b)

print(a)
print(b)
print(c)

[[3 1 9 3]
 [6 6 1 5]
 [8 1 1 4]]
[9 7 6 9]
[115 147 121]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [38]:
a = np.random.rand(2, 3)
b = np.random.rand(3)
c = np.dot(a, b)

print(a)
print(b)
print(c)

[[0.97211184 0.35323319 0.63368324]
 [0.98221762 0.0797355  0.19763159]]
[0.12931427 0.40954394 0.55997827]
[0.62522129 0.27033934]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [39]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = a*b

print(a)
print(b)
print(c)

[[1 3]
 [3 7]]
[[5 1]
 [1 6]]
[[ 5  3]
 [ 3 42]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.



In [40]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)

print(a)
print(b)
print(c)

[[6 1]
 [5 5]]
[[7 4]
 [7 9]]
[[49 33]
 [70 65]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [44]:
a = np.random.randint(1, 101, size=(5, 5))
c = np.sum(a)

print(a)
print(c)

[[62 57 43  4 94]
 [61 61 40 39  3]
 [67  1 14 76 59]
 [88 42 77 56 17]
 [ 2 79 23 25  1]]
1091
